// doomrpg_sounds
// Copyright(C) 2020-2022 John D. Corrado
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

#ifndef __DOOMRPG_SOUNDS_H__
#define __DOOMRPG_SOUNDS_H__

#define SOUND_UNKNOWN_1					"002"
#define SOUND_AXE						"004"
#define SOUND_FIRE_EXT					"005"
#define SOUND_PISTOL					"006"
#define SOUND_SHOTGUN					"007"
#define SOUND_CHAINGUN					"008"
#define SOUND_SUPER_SHOTGN				"009"
#define SOUND_PLASMA_GUN				"010"
#define SOUND_ROCKET_LNCHR				"011"
#define SOUND_BFG						"012"
#define SOUND_HELLHOUND_WPN				"013"
#define SOUND_CERBERUS_WPN				"014"
#define SOUND_DEMON_WOLF_WPN			"015"
#define SOUND_WEAPON_PICKUP				"016"
#define SOUND_PLAYER_DEATH_1			"017"
#define SOUND_PLAYER_DEATH_2			"018"
#define SOUND_ITEM_PICKUP				"019"
#define SOUND_BARREL_EXPLOSION			"020"
#define SOUND_POWERUP_PICKUP			"021"
#define SOUND_DOOR_OPEN					"022"
#define SOUND_DOOR_CLOSE				"023"
#define SOUND_NO_USE					"024"
#define SOUND_TELEPORT					"025"
#define SOUND_SWITCH_1					"026"
#define SOUND_SWITCH_2					"027"
#define SOUND_IMP_ROAM					"028"
#define SOUND_IMP_SIGHT_1				"029"
#define SOUND_IMP_SIGHT_2				"030"
#define SOUND_IMP_ATTACK_1				"031"
#define SOUND_IMP_ATTACK_2				"032"
#define SOUND_IMP_PAIN					"033"
#define SOUND_IMP_DEATH_1				"034"
#define SOUND_IMP_DEATH_2				"035"
#define SOUND_ZOMBIE_ROAM				"036"
#define SOUND_ZOMBIE_SIGHT_1			"037"
#define SOUND_ZOMBIE_SIGHT_2			"038"
#define SOUND_PLAYER_PAIN				"039"
#define SOUND_ZOMBIE_DEATH_1			"040"
#define SOUND_ZOMBIE_PAIN_1				"041"
#define SOUND_ZOMBIE_DEATH_2			"042"
#define SOUND_ZOMBIE_PAIN_2				"043"
#define SOUND_DOG_ROAM					"044"
#define SOUND_DOG_SIGHT					"045"
#define SOUND_DOG_ATTACK				"046"
#define SOUND_DOG_PAIN					"047"
#define SOUND_DOG_DEATH					"048"
#define SOUND_GIB						"049"
#define SOUND_DEMON_ROAM_1				"050"
#define SOUND_DEMON_SIGHT				"051"
#define SOUND_DEMON_ATTACK				"052"
#define SOUND_DEMON_DEATH				"053"
#define SOUND_CACODEMON_ATTACK			"054"
#define SOUND_CACODEMON_SIGHT			"055"
#define SOUND_DEMON_ROAM_2				"056"
#define SOUND_CACODEMON_PAIN			"057"
#define SOUND_LOST_SOUL_ATTACK			"058"
#define SOUND_FIREBALL_EXPLOSION		"059"
#define SOUND_CACODEMON_DEATH			"060"
#define SOUND_REVENANT_SIGHT			"061"
#define SOUND_REVENANT_ROAM				"062"
#define SOUND_REVENANT_ATTACK_1			"063"
#define SOUND_ZOMBIE_SIGHT_3			"064"
#define SOUND_ZOMBIE_DEATH_3			"065"
#define SOUND_DEMON_ROAM_3				"066"
#define SOUND_PAIN_ELEMENTAL_SIGHT		"067"
#define SOUND_PAIN_ELEMENTAL_PAIN		"068"
#define SOUND_PAIN_ELEMENTAL_DEATH		"069"
#define SOUND_REVENANT_ATTACK_2			"070"
#define SOUND_REVENANT_DEATH			"071"
#define SOUND_REVENANT_SWING			"072"
#define SOUND_MANCUBUS_SIGHT			"073"
#define SOUND_MANCUBUS_ATTACK			"074"
#define SOUND_MANCUBUS_PAIN				"075"
#define SOUND_MANCUBUS_DEATH			"076"
#define SOUND_ARCHVILE_ROAM				"077"
#define SOUND_ARCHVILE_SIGHT			"078"
#define SOUND_ARCHVILE_ATTACK			"079"
#define SOUND_ARCHVILE_PAIN				"080"
#define SOUND_ARCHVILE_DEATH			"081"
#define SOUND_HELLSPAWN_RESURRECTION	"082"
#define SOUND_BARON_SIGHT				"083"
#define SOUND_BARON_DEATH				"084"
#define SOUND_CYBERDEMON_ROAM			"085"
#define SOUND_CYBERDEMON_SIGHT			"086"
#define SOUND_CYBERDEMON_DEATH			"087"
#define SOUND_BFG_EXPLOSION				"088"
#define SOUND_FIRE						"089"
#define SOUND_SECRET					"090"
#define SOUND_UNKNOWN_2					"091"
#define SOUND_UNKNOWN_3					"092"
#define SOUND_KRONOS_PAIN				"093"
#define SOUND_KRONOS_DEATH				"094"

#endif